/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    borderRadius: {
      'none': '0px',
      'sm': '0px',
      DEFAULT: '0px',
      'md': '0px',
      'lg': '0px',
      'xl': '0px',
      '2xl': '0px',
      '3xl': '0px',
      'full': '9999px',
    },
    extend: {
      colors: {
        primary: {
          50: '#e8f2fd',
          100: '#c5defb',
          200: '#9ec7f7',
          300: '#6bbce8',
          400: '#3b8fd4',
          500: '#1b4d8e',
          600: '#163f76',
          700: '#11305e',
          800: '#0d1c38',
          900: '#091530',
          950: '#050d22',
        },
        sidebar: {
          bg: '#091530',
          hover: '#0d1c38',
          active: '#1b4d8e',
        },
        // Material Design 3 Dark Theme - Sora POS Enterprise
        sora: {
          bg: '#0b1326',
          'surface': '#0b1326',
          'surface-dim': '#0b1326',
          'surface-container': '#171f33',
          'surface-container-low': '#131b2e',
          'surface-container-high': '#222a3d',
          'surface-container-highest': '#2d3449',
          'surface-container-lowest': '#060e20',
          'surface-bright': '#31394d',
          'surface-variant': '#2d3449',
          'on-bg': '#dae2fd',
          'on-surface': '#dae2fd',
          'on-surface-variant': '#c1c7d3',
          'primary': '#a4c9ff',
          'primary-container': '#60a5fa',
          'on-primary': '#00315d',
          'on-primary-container': '#003a6b',
          'outline': '#8b919d',
          'outline-variant': '#414751',
          'error': '#ffb4ab',
          'error-container': '#93000a',
          'on-error': '#690005',
          'on-error-container': '#ffdad6',
          'secondary': '#b9c8de',
          'tertiary': '#b9c7e0',
          'inverse-surface': '#dae2fd',
          'inverse-primary': '#0060ac',
        },
      },
      fontFamily: {
        sans: ['Montserrat', 'Arial', 'Helvetica', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      animation: {
        'shake': 'shake 0.5s ease-in-out',
        'float': 'float 3s ease-in-out infinite',
        'fadeIn': 'fadeIn 0.4s ease-out',
        'slideUp': 'slideUp 0.6s cubic-bezier(0.16, 1, 0.3, 1)',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        'scan-line': 'scanLine 4s linear infinite',
      },
      keyframes: {
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-5px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(5px)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 15px rgba(96, 165, 250, 0.15)' },
          '50%': { boxShadow: '0 0 30px rgba(96, 165, 250, 0.3)' },
        },
        scanLine: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
      },
    },
  },
  plugins: [],
};
